[package]
name = "docker-password-aya-common"
version = "0.1.0"
edition = "2018"

[features]
default = []
user = [ "aya" ]

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", commit="923cd9b7679ee03d0ebe884588eb0a8f984b65f0", optional=true }

[lib]
path = "src/lib.rs"